# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FFSXqZJWSmZ9KunQzYt5ZpjCq-eo96Di
"""

! wget https://raw.githubusercontent.com/alok676875/RDP/main/RDP.sh &> /dev/null
! ls
! chmod +x RDP.sh 
! ./RDP.sh